### ISSUE TITLE
Issue While connection the kibana

### ISSUE THREAD

**Issue by rkstar007** [abutaha/aws-es-proxy#20]
Hello ,

I follow your step and in browser i am not able to access the kibana URL.All Traffic is allowed to security group for 9200 port.

Here I am running EC2 instance with instance profile who has role associated with **ES-FULL-ROLE** 

My Resource Based Policy : 
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::111111111111:role/ES-FULL-ROLE"
      },
      "Action": "es:*",
      "Resource": "arn:aws:es:us-east-1:111111111111:domain/rkteam1/*"
    }
  ]
}

My IAM Policy : 

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "es:*"
            ],
            "Resource": "arn:aws:es:us-east-1:111111111111:domain/*",
            "Effect": "Allow"
        },
        {
            "Effect": "Allow",
            "Action": "iam:PassRole",
            "Resource": "arn:aws:iam::111111111111:role/ES-FULL-ROLE"
        }
    ]
}

OUTPUT :

[root@ip-172-31-65-132 aws-es-proxy]# ./aws-es-proxy -verbose  -listen 127.0.0.1:9200 -endpoint https://search-rkteam1-3lpw44lsn6ez4hccim6w66pj3e.us-east-1.es.amazonaws.com ; tail -f /var/log/messages
2018/01/19 08:30:53 Listening on 127.0.0.1:9200...

[](https://s3.amazonaws.com/skimpdocs/Kibana.png
)

Regards,
RK

**Comment by abutaha** [comment]
Hi, this is because the proxy is running on your localhost IP. You need to make it run like the following:

./aws-es-proxy -verbose -listen *0.0.0.0:9200* -endpoint https://search-rkteam1-3lpw44lsn6ez4hccim6w66pj3e.us-east-1.es.amazonaws.com

or 

./aws-es-proxy -verbose -listen *172.31.65.132:9200* -endpoint https://search-rkteam1-3lpw44lsn6ez4hccim6w66pj3e.us-east-1.es.amazonaws.com

172.31.65.132: Is your EC2 instance private IP.
