### ISSUE TITLE
Kibana blank page

### ISSUE THREAD

**Issue by mertkiray** [abutaha/aws-es-proxy#57]
Hello, is this project still maintained? 
Kibana page stays as blank when loaded by the proxy. 
Do you plan to release v.1.0 soon or are there any hacks to fix this. 
Thanks, 
My ES specs is this:
 `{
  "name" : "xxxx",
  "cluster_name" : "xxxx",
  "cluster_uuid" : "xxxx",
  "version" : {
    "number" : "7.1.1",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "7a013de",
    "build_date" : "2019-09-05T07:25:23.525600Z",
    "build_snapshot" : false,
    "lucene_version" : "8.0.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}`

**Comment by abutaha** [comment]
Hi @mertkiray,

Yes, the project is still maintained. There's a dev branch for v1.0, but it's not ready to be released yet.

The recent versions of Kibana are returning 302s for **_plugin/kibana** pointing to **_plugin/kibana/app/kibana**. This change is making the signing request to fail.

However, if you request Kibana through the link directly it works. So instead of accessing: http://localhost:9200/_plugin/kibana try accessing http://localhost:9200/_plugin/kibana/app/kibana

Thanks

**Comment by abutaha** [comment]
This issue has been fixed in master branch now. A docker image will follow soon.
